### ISSUE TITLE
Rapidfire Issues #1: Desynced rapidfire

### ISSUE THREAD

**Issue by RSw-Why** [Mupen64-Rewrite/TASInput#3]
In TASInput, when you begin rapidfire, the box checks correctly, but then the next frame it stays ticked. After this, it checks and unchecks the box "correctly", except it is desynced from the game 

(so for example mario will jump when the box is unchecked and you frame advance, and then do nothing when the box is checked)

this can really throw you off when doing stuff like 0 input bljs.

attatched a video demonstrating the issue. you can see that the check box unchecks a frame late after activating rapidfire, and that mario will jump when the box is unchecked, and not jump when the box is checked.

https://github.com/Mupen64-Rewrite/TASInput/assets/65158808/a9ef514e-033b-4346-97de-8523cff68e91

intended behaviour is that the checkbox disappears after you advance a frame, and that mario jumps when you advance a frame and the box is checked.

**Comment by Aurumaker72** [comment]
Closed by 6150d00f42b3c70430f6cf6448bf8775032596ba and 847c5b55e643ee06cd5c37ea996cfc41a4d50575
