### ISSUE TITLE
Rapidfire issues #2: Holding right click

### ISSUE THREAD

**Issue by RSw-Why** [Mupen64-Rewrite/TASInput#4]
In TASinput, when you right click a button, you enable rapidfire mode. However, when you move your mouse with right click held, even slightly, it treats it as a new "right click". this means that sometimes, when right clicking for rapidfire and you accidentally move the mouse slightly, you can sometimes cause it to quickly disable the rapidfire, meaning you have to enable it again. I have memories of me having to right click sometimes 3 or 4 times to get rapidfire going.

This issue was frustrating enough for me that i had to revert to an old version of "new TASinput" for normal behaviour.

attatched vid show this issue

https://github.com/Mupen64-Rewrite/TASInput/assets/65158808/e471143c-a118-4cf8-a9d9-30672eb78c5c

**Comment by Aurumaker72** [comment]
Closed by 3da134ca63e0296095314439e81df53917fb9f52
