### ISSUE TITLE
TASinput focus issue

### ISSUE THREAD

**Issue by RSw-Why** [Mupen64-Rewrite/TASInput#5]
TASinput fixes focus issue that windows decided to introduce.

TASinput mostly fixes this, but sometimes if your mouse click is quick enough, focus does not return to mupen.

this only seems to happen when clicking a blank area of tasinput, never happens with buttons or joystick area, however it can be annoying if i miss a button and causes mupen to unfocus, which sometimes happens when i quickly adjust angles using the buttons.

attatched vid

https://github.com/Mupen64-Rewrite/TASInput/assets/65158808/08fea2e2-ba7b-4f32-b8e7-a2a67e38e6cb

**Comment by Aurumaker72** [comment]
Can't repro on latest commit
