### ISSUE TITLE
Newest version of TASinput messes up previous versions of TASinput.

### ISSUE THREAD

**Issue by RSw-Why** [Mupen64-Rewrite/TASInput#6]
After updating to and using the newest version of TASinput released in this repo, which is also released in the mupen 1.1.5 release, i have since observed a strange effect on older versions of tasinput.

normally, tasinput opens up as a square window with the buttons and the joystick open as default. this has been the case ever since tasinput 0.6. however ever since running the new tasinput, (which opens perfectly fine) older versions do not do the same.

attatched vid to show what happens with older versions vs newest. i use 0.6 in the vid but the same applies for one of the versions of tasinput released in 2020.

https://github.com/Mupen64-Rewrite/TASInput/assets/65158808/c8c39615-012e-4880-9632-92db7c0ee43c

not a programmer but my theory is that it has something to do with the removal of the "hide" buttons.

this issue wont really be an issue if there became no real reason to use older versions over this one.

**Comment by Aurumaker72** [comment]
Closed by 4f52fa3edb110cc480f5318efe3942cadb8a8bd0
