### ISSUE TITLE
Previous analog stick coordinates are not cleared when an analog stick hotkey is pressed and released

### ISSUE THREAD

**Issue by Wade7wastaken** [Mupen64-Rewrite/TASInput#9]
Analog stick coordinates that are set by moving the stick with the mouse persist when analog stick hotkeys are pressed. The axis of the hotkey is reset to zero when the hotkey is released, but the perpendicular axis remains the same.

Coordinates set with mouse
![image](https://github.com/Mupen64-Rewrite/TASInput/assets/86390605/92ac13b9-1ab5-43db-97a1-9591dc58bbdf)

Up hotkey currently being pressed
![image](https://github.com/Mupen64-Rewrite/TASInput/assets/86390605/0226db78-3710-421b-87ac-a009ed7f1ee3)

Up hotkey released
![image](https://github.com/Mupen64-Rewrite/TASInput/assets/86390605/92b3300a-50a2-4555-8ca7-c482733897f4)

### Expected behavior:
All previous analog stick coordinates an all axes should be reset when any hotkey is pressed.

**Comment by Aurumaker72** [comment]
This is intended.
